import Head from 'next/head'
import axios from 'axios'
import Link from 'next/link'


export default function Home({ currentUser, tickets }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <h4>Tickets</h4>
        <table className="table">
          <thead>
            <tr>
              <th>Title</th>
              <th>Price</th>
              <th>Link</th>
            </tr>
          </thead>
          <tbody>
            {tickets.map(ticket => (
              <tr key={ticket.id}>
                <td>{ticket.title}</td>
                <td>{ticket.price}</td>
                <td><Link href={`/ticket/${ticket.id}`} className='btn btn-sm btn-secondary'>View</Link></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  )
}

export async function getServerSideProps(context) {
  const res = await axios.get("http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/tickets", {
    headers: context.req.headers
  })
  return {
    props: {
      tickets: res.data
    }
  }
}